# Generated by Django 5.0.2 on 2024-02-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pquantity',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ptotalprice',
            field=models.CharField(default=50, max_length=10),
        ),
    ]
