# Generated by Django 5.0.1 on 2024-02-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_rename_fname_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
    ]
