# Generated by Django 5.0.1 on 2024-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0006_signupinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinfo',
            name='pswd',
            field=models.CharField(max_length=30),
        ),
    ]
