# Generated by Django 5.0.1 on 2024-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0007_alter_signupinfo_pswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
